// <auto-generated />
using System;
using JustBlog.Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustBlog.Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JustBlog.Entities.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("56de49b5-22c6-4e3e-8e8c-6adb86a24cc9"),
                            AccessFailedCount = 0,
                            Age = 0,
                            ConcurrencyStamp = "bc586de8-dfa3-4064-97ef-09495799e805",
                            Email = "user@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@EXAMPLE.COM",
                            NormalizedUserName = "USER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOzFmC2uIv07b5lo5n1ZfUXn17x4uIcA5os+tGHA6J9QJwYm8pVNh2GMrSFbeR1n4w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user@example.com"
                        },
                        new
                        {
                            Id = new Guid("ac924737-2076-4cab-983a-f184ef7f2f1b"),
                            AccessFailedCount = 0,
                            Age = 0,
                            ConcurrencyStamp = "80cb8cda-8d32-41dc-80b6-54b44e55c5cb",
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE/LQO8ken9vxIR/HeZdayFESKX9SwGscFhOfQSUZrK3RL6AlmQEVFeqAZAd1tB5Wg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user1@example.com"
                        },
                        new
                        {
                            Id = new Guid("da1d155d-2eb4-46ad-81ed-ddd99ea58b4e"),
                            AccessFailedCount = 0,
                            Age = 0,
                            ConcurrencyStamp = "9d45d780-586c-427d-8972-2f5a491dd4ef",
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDPpyYL3JO1F4WBzQw9ltvOOF5DaniRlB6haMl1jmR7G1s08g25YgCC8XrVeD5qkng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user2@example.com"
                        },
                        new
                        {
                            Id = new Guid("1c917bbc-383b-4b7e-9fce-bfd76f2f4aed"),
                            AccessFailedCount = 0,
                            Age = 0,
                            ConcurrencyStamp = "7f8a2d0d-a8d5-42b7-acf9-c3f7d480734b",
                            Email = "owner@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER@EXAMPLE.COM",
                            NormalizedUserName = "OWNER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIopP7+OCO0HXOtfK8T9cVe05SVwUcCLtrbUtpqQV/KmwWWdS3GtvsvE/SY16QInFw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "owner@example.com"
                        },
                        new
                        {
                            Id = new Guid("c92627c0-9156-494d-bc90-ad381f136852"),
                            AccessFailedCount = 0,
                            Age = 0,
                            ConcurrencyStamp = "dd2c0ff9-e382-4759-a6d2-d14db6b9f260",
                            Email = "owner1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER1@EXAMPLE.COM",
                            NormalizedUserName = "OWNER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEB4QUjTA/Bssa3HHN1A34/mn7LLt/X3wGMY9V1YuMAmgGYSv3wNZy+6ePy0njVozfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "owner1@example.com"
                        },
                        new
                        {
                            Id = new Guid("55c97cf2-48a1-455c-80e0-307cca32e4fa"),
                            AccessFailedCount = 0,
                            Age = 0,
                            ConcurrencyStamp = "4a55d38a-a30f-43ab-a296-63df9087a7aa",
                            Email = "owner2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER2@EXAMPLE.COM",
                            NormalizedUserName = "OWNER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJz2pNUAztA1FJtBEAHijMMho25QLTesAr3amPiTmUrITAdmeMQP2zenO/NZo+NKMQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "owner2@example.com"
                        },
                        new
                        {
                            Id = new Guid("8b5ed246-11b1-4df6-b36a-9be399f60891"),
                            AccessFailedCount = 0,
                            Age = 0,
                            ConcurrencyStamp = "0de52d97-cf5f-46d5-91ef-fd4719d92514",
                            Email = "contributor@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CONTRIBUTOR@EXAMPLE.COM",
                            NormalizedUserName = "CONTRIBUTOR@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIF3UlkB6sasH5Z/sy+G6f7XKnPJce9bAptkvlNrnLDIMaCUkcxn29QFyWb2VmDH8Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "contributor@example.com"
                        },
                        new
                        {
                            Id = new Guid("aeae5ff8-43cd-4f90-8d9e-234b9c2d14b9"),
                            AccessFailedCount = 0,
                            Age = 0,
                            ConcurrencyStamp = "69cf780f-bd6a-4a6d-a7a0-fd45db9cb760",
                            Email = "contributor1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CONTRIBUTOR1@EXAMPLE.COM",
                            NormalizedUserName = "CONTRIBUTOR1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEItM6Q/0/px725XSVGmAaDMYkAusewBwHd8gFXmpcQGZ+jzl2y1JG1sSZ3erVFhY3g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "contributor1@example.com"
                        },
                        new
                        {
                            Id = new Guid("70369848-8782-4928-b8e3-106db74c5f3f"),
                            AccessFailedCount = 0,
                            Age = 0,
                            ConcurrencyStamp = "5c1bd9a1-7dfa-4ab4-ab34-b44e68b71d9b",
                            Email = "contributor2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CONTRIBUTOR2@EXAMPLE.COM",
                            NormalizedUserName = "CONTRIBUTOR2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECOkHh6YOZGA4lyaOc4VCZHoKjiApVAINAukK37ED4INMkHViGNxcfHtsZAIzuvttQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "contributor2@example.com"
                        });
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlSlug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UrlSlug")
                        .IsUnique()
                        .HasFilter("[UrlSlug] IS NOT NULL");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf2a84ab-68f7-482d-8dcd-f2c0f9028049"),
                            Description = "Description 1",
                            Name = "Category 1",
                            UrlSlug = "category-1"
                        },
                        new
                        {
                            Id = new Guid("e1a767ca-708a-4392-bf9a-c16dcf9ab04f"),
                            Description = "Description 2",
                            Name = "Category 2",
                            UrlSlug = "category-2"
                        },
                        new
                        {
                            Id = new Guid("4245cf7a-4aa2-4467-b411-518830a4a43a"),
                            Description = "Description 3",
                            Name = "Category 3",
                            UrlSlug = "category-3"
                        });
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<int>("RateCount")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalRate")
                        .HasColumnType("int");

                    b.Property<string>("UrlSlug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UrlSlug")
                        .IsUnique()
                        .HasFilter("[UrlSlug] IS NOT NULL");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37026059-494f-499e-ac1a-17fb1f8736b0"),
                            CategoryId = new Guid("bf2a84ab-68f7-482d-8dcd-f2c0f9028049"),
                            Content = "Content 1",
                            Description = "Description 1",
                            Modified = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostedOn = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Short Description 1",
                            Title = "Post 1",
                            TotalRate = 10,
                            UrlSlug = "post-1",
                            ViewCount = 2
                        },
                        new
                        {
                            Id = new Guid("8d248b4b-2a7d-4a85-a2d9-9688ce5aa9a2"),
                            CategoryId = new Guid("e1a767ca-708a-4392-bf9a-c16dcf9ab04f"),
                            Content = "Content 2",
                            Description = "Description 2",
                            Modified = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostedOn = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 5,
                            ShortDescription = "Short Description 2",
                            Title = "Post 2",
                            TotalRate = 15,
                            UrlSlug = "post-2",
                            ViewCount = 5
                        },
                        new
                        {
                            Id = new Guid("274ccdc9-922d-42d3-9931-5448b6a21f21"),
                            CategoryId = new Guid("4245cf7a-4aa2-4467-b411-518830a4a43a"),
                            Content = "Content 3",
                            Description = "Description 3",
                            Modified = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostedOn = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 10,
                            ShortDescription = "Short Description 3",
                            Title = "Post 3",
                            TotalRate = 10,
                            UrlSlug = "post-3",
                            ViewCount = 10
                        });
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.PostTagMap", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTags");

                    b.HasData(
                        new
                        {
                            PostId = new Guid("37026059-494f-499e-ac1a-17fb1f8736b0"),
                            TagId = new Guid("bc341849-ae9c-4dc6-8735-ac10d1d76ac1")
                        },
                        new
                        {
                            PostId = new Guid("37026059-494f-499e-ac1a-17fb1f8736b0"),
                            TagId = new Guid("90ee6cd8-7e27-43ea-95a2-1cb21edff54e")
                        },
                        new
                        {
                            PostId = new Guid("8d248b4b-2a7d-4a85-a2d9-9688ce5aa9a2"),
                            TagId = new Guid("90ee6cd8-7e27-43ea-95a2-1cb21edff54e")
                        },
                        new
                        {
                            PostId = new Guid("8d248b4b-2a7d-4a85-a2d9-9688ce5aa9a2"),
                            TagId = new Guid("48c1c139-b86e-4811-899b-05d81814a394")
                        },
                        new
                        {
                            PostId = new Guid("274ccdc9-922d-42d3-9931-5448b6a21f21"),
                            TagId = new Guid("48c1c139-b86e-4811-899b-05d81814a394")
                        },
                        new
                        {
                            PostId = new Guid("274ccdc9-922d-42d3-9931-5448b6a21f21"),
                            TagId = new Guid("bc341849-ae9c-4dc6-8735-ac10d1d76ac1")
                        });
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlSlug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UrlSlug")
                        .IsUnique()
                        .HasFilter("[UrlSlug] IS NOT NULL");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc341849-ae9c-4dc6-8735-ac10d1d76ac1"),
                            Description = "Description 1",
                            Name = "Tag 1",
                            UrlSlug = "tag-1"
                        },
                        new
                        {
                            Id = new Guid("90ee6cd8-7e27-43ea-95a2-1cb21edff54e"),
                            Description = "Description 2",
                            Name = "Tag 2",
                            UrlSlug = "tag-2"
                        },
                        new
                        {
                            Id = new Guid("48c1c139-b86e-4811-899b-05d81814a394"),
                            Description = "Description 3",
                            Name = "Tag 3",
                            UrlSlug = "tag-3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9d69a07-8601-4d43-8e80-190e97bb068f"),
                            Name = "Blog Owner",
                            NormalizedName = "BLOG OWNER"
                        },
                        new
                        {
                            Id = new Guid("9b47fbf8-e0b6-48af-8fa9-3636c7f815ec"),
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("dc71a2ee-5450-4827-a74a-4ee47043450b"),
                            Name = "Contributor",
                            NormalizedName = "CONTRIBUTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("55c97cf2-48a1-455c-80e0-307cca32e4fa"),
                            RoleId = new Guid("e9d69a07-8601-4d43-8e80-190e97bb068f")
                        },
                        new
                        {
                            UserId = new Guid("c92627c0-9156-494d-bc90-ad381f136852"),
                            RoleId = new Guid("e9d69a07-8601-4d43-8e80-190e97bb068f")
                        },
                        new
                        {
                            UserId = new Guid("1c917bbc-383b-4b7e-9fce-bfd76f2f4aed"),
                            RoleId = new Guid("e9d69a07-8601-4d43-8e80-190e97bb068f")
                        },
                        new
                        {
                            UserId = new Guid("56de49b5-22c6-4e3e-8e8c-6adb86a24cc9"),
                            RoleId = new Guid("9b47fbf8-e0b6-48af-8fa9-3636c7f815ec")
                        },
                        new
                        {
                            UserId = new Guid("ac924737-2076-4cab-983a-f184ef7f2f1b"),
                            RoleId = new Guid("9b47fbf8-e0b6-48af-8fa9-3636c7f815ec")
                        },
                        new
                        {
                            UserId = new Guid("da1d155d-2eb4-46ad-81ed-ddd99ea58b4e"),
                            RoleId = new Guid("9b47fbf8-e0b6-48af-8fa9-3636c7f815ec")
                        },
                        new
                        {
                            UserId = new Guid("70369848-8782-4928-b8e3-106db74c5f3f"),
                            RoleId = new Guid("dc71a2ee-5450-4827-a74a-4ee47043450b")
                        },
                        new
                        {
                            UserId = new Guid("aeae5ff8-43cd-4f90-8d9e-234b9c2d14b9"),
                            RoleId = new Guid("dc71a2ee-5450-4827-a74a-4ee47043450b")
                        },
                        new
                        {
                            UserId = new Guid("8b5ed246-11b1-4df6-b36a-9be399f60891"),
                            RoleId = new Guid("dc71a2ee-5450-4827-a74a-4ee47043450b")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Comment", b =>
                {
                    b.HasOne("JustBlog.Entities.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Post", b =>
                {
                    b.HasOne("JustBlog.Entities.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.PostTagMap", b =>
                {
                    b.HasOne("JustBlog.Entities.Entities.Post", "Post")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustBlog.Entities.Entities.Tag", "Tag")
                        .WithMany("PostTag")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("JustBlog.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("JustBlog.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustBlog.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("JustBlog.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostTagMaps");
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Tag", b =>
                {
                    b.Navigation("PostTag");
                });
#pragma warning restore 612, 618
        }
    }
}
